/**
 * Project-level scaffold templates.
 * These are written once when `zakarya create` runs.
 */

// ─── shared/api/client.ts ─────────────────────────────────────────────────────

export const apiClientTemplate = (baseUrl: string, timeout: number): string => `
/**
 * Shared Axios Client
 *
 * Single Axios instance for the entire application.
 * ALL features must use this — never instantiate Axios directly.
 *
 * Interceptors:
 *  - Request: attaches Authorization header (if token present in storage)
 *  - Response: normalizes errors through AppError
 */

import axios, { AxiosError, type InternalAxiosRequestConfig } from 'axios';
import { AppError } from '../errors/app.error';

export const apiClient = axios.create({
  baseURL: process.env.NEXT_PUBLIC_API_URL ?? '${baseUrl}',
  timeout: ${timeout},
  headers: {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  },
});

// ── Request interceptor ────────────────────────────────────────────────────────
apiClient.interceptors.request.use(
  (config: InternalAxiosRequestConfig) => {
    // [zakarya:inject:request-interceptor]
    const token =
      typeof window !== 'undefined' ? localStorage.getItem('access_token') : null;

    if (token && config.headers) {
      config.headers.Authorization = \`Bearer \${token}\`;
    }

    return config;
  },
  (error: unknown) => Promise.reject(error)
);

// ── Response interceptor ───────────────────────────────────────────────────────
apiClient.interceptors.response.use(
  (response) => response,
  async (error: AxiosError<{ message?: string; errors?: unknown }>) => {
    const status = error.response?.status ?? 0;
    const serverMessage = error.response?.data?.message ?? error.message;

    // [zakarya:inject:response-interceptor]

    if (status === 401) {
      // Token expired — clear storage and redirect to login
      if (typeof window !== 'undefined') {
        localStorage.removeItem('access_token');
        window.location.href = '/login';
      }
    }

    return Promise.reject(
      new AppError(serverMessage, status, error.response?.data?.errors)
    );
  }
);
`.trimStart();

// ─── shared/api/endpoints.constants.ts ───────────────────────────────────────

export const endpointsTemplate = (): string => `
/**
 * API Endpoints
 *
 * All endpoint base paths in one place.
 * Generated by zakarya — add new endpoints here or run:
 *   zakarya generate feature <name>
 */

export const ENDPOINTS = {
  // [zakarya:inject:endpoints]
  AUTH: '/auth',
} as const;

export type EndpointKey = keyof typeof ENDPOINTS;
`.trimStart();

// ─── shared/errors/app.error.ts ───────────────────────────────────────────────

export const appErrorTemplate = (): string => `
/**
 * AppError
 *
 * Normalized application error.
 * All errors surfaced from the Axios client are instances of AppError.
 */

export class AppError extends Error {
  public readonly status: number;
  public readonly details: unknown;

  constructor(message: string, status: number, details?: unknown) {
    super(message);
    this.name = 'AppError';
    this.status = status;
    this.details = details;

    // Fix prototype chain for transpiled TypeScript
    Object.setPrototypeOf(this, new.target.prototype);
  }

  get isNotFound(): boolean {
    return this.status === 404;
  }

  get isUnauthorized(): boolean {
    return this.status === 401;
  }

  get isForbidden(): boolean {
    return this.status === 403;
  }

  get isServerError(): boolean {
    return this.status >= 500;
  }

  get isNetworkError(): boolean {
    return this.status === 0;
  }

  toJSON() {
    return {
      name: this.name,
      message: this.message,
      status: this.status,
      details: this.details,
    };
  }
}
`.trimStart();

// ─── shared/tanstack/query-client.ts ─────────────────────────────────────────

export const queryClientTemplate = (
  staleTime: number,
  gcTime: number,
  retry: boolean | number,
  refetchOnWindowFocus: boolean
): string => `
/**
 * TanStack Query — Shared QueryClient
 *
 * Single QueryClient instance used by QueryClientProvider.
 * All global defaults are configured here.
 */

import { QueryClient } from '@tanstack/react-query';
import { AppError } from '../errors/app.error';

function makeQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: {
        staleTime: ${staleTime},
        gcTime: ${gcTime},
        retry: (failureCount, error) => {
          if (error instanceof AppError && (error.isUnauthorized || error.isForbidden || error.isNotFound)) {
            return false; // Don't retry auth/permission/404 errors
          }
          return failureCount < ${typeof retry === 'boolean' ? (retry ? 1 : 0) : retry};
        },
        refetchOnWindowFocus: ${refetchOnWindowFocus},
        throwOnError: false,
      },
      mutations: {
        retry: false,
        throwOnError: false,
      },
    },
  });
}

let browserQueryClient: QueryClient | undefined;

/**
 * Returns the shared QueryClient.
 * On the server a new instance is created per-request.
 * On the client a singleton is maintained.
 */
export function getQueryClient(): QueryClient {
  if (typeof window === 'undefined') {
    return makeQueryClient();
  }

  if (!browserQueryClient) {
    browserQueryClient = makeQueryClient();
  }

  return browserQueryClient;
}
`.trimStart();

// ─── shared/tanstack/providers.tsx ────────────────────────────────────────────

export const queryProviderTemplate = (): string => `
/**
 * QueryClientProvider wrapper
 *
 * Wrap your root layout with <QueryProvider> to enable TanStack Query.
 */

'use client';

import { useState } from 'react';
import { QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { getQueryClient } from './query-client';

interface QueryProviderProps {
  children: React.ReactNode;
}

export function QueryProvider({ children }: QueryProviderProps) {
  const [queryClient] = useState(getQueryClient);

  return (
    <QueryClientProvider client={queryClient}>
      {children}
      {process.env.NODE_ENV === 'development' && (
        <ReactQueryDevtools initialIsOpen={false} />
      )}
    </QueryClientProvider>
  );
}
`.trimStart();

// ─── app/layout.tsx ───────────────────────────────────────────────────────────

export const rootLayoutTemplate = (projectName: string): string => `
import type { Metadata } from 'next';
import { QueryProvider } from '@/shared/tanstack/providers';
import './globals.css';

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by zakarya',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
`.trimStart();

// ─── app/page.tsx ─────────────────────────────────────────────────────────────

export const rootPageTemplate = (projectName: string): string => `
export default function HomePage() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>Welcome to <strong>${projectName}</strong></h1>
      <p>Generated by <code>zakarya</code> — Next.js App Router + TanStack Query + Axios</p>
      <ul>
        <li>Add features: <code>zakarya generate feature &lt;name&gt;</code></li>
        <li>Add CRUD resource: <code>zakarya generate resource &lt;name&gt;</code></li>
      </ul>
    </main>
  );
}
`.trimStart();

// ─── next.config.ts ───────────────────────────────────────────────────────────

export const nextConfigTemplate = (): string => `
import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  // Strict mode on for development warnings
  reactStrictMode: true,

  // Bundle analysis (run: ANALYZE=true next build)
  ...(process.env.ANALYZE === 'true' && {
    experimental: {},
  }),
};

export default nextConfig;
`.trimStart();

// ─── tsconfig.json (generated project) ───────────────────────────────────────

export const projectTsConfigTemplate = (): string =>
  JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        baseUrl: '.',
        paths: { '@/*': ['./src/*'] },
        noUnusedLocals: true,
        noUnusedParameters: true,
        noImplicitReturns: true,
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    },
    null,
    2
  );
